resolver: lts-14.16 # Adapt this as needed
packages:
  - .
extra-deps:
  - hakyll-4.13.3.0 # Or a later version you installed
  - hakyll-sass-0.2.4@sha256:4d2fbd8b63f5ef15483fc6dda09e10eefd63b4f873ad38dec2a3607eb504a8ba,939
